"""
Django settings for email_project project.

Generated by 'django-admin startproject' using Django 5.0.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gowxkim1e6(#$_xid@6rw3e7fvcv(&7h%p29&$o2keh25%i*wo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['hassen86naghmouchi.pythonanywhere.com', 'localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'email_api',  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    
    # CRITICAL FIX: The CorsMiddleware must be placed before 
    # CommonMiddleware and CsrfViewMiddleware to handle the OPTIONS preflight.
    'corsheaders.middleware.CorsMiddleware', 
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'email_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'email_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

#STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Le reste des configurations statiques (déjà présentes)
STATIC_URL = '/static/'
# ...existing code...
import os
# 1. Votre adresse Gmail
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'kodikids.info@gmail.com' 
# 2. Le MOT DE PASSE D'APPLICATION à 16 caractères (NE PAS UTILISER VOTRE MOT DE PASSE HABITUEL)
EMAIL_HOST_PASSWORD = 'lyat cnjl vjds gjpo' 
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
#EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
#EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')  # votre adresse Gmail
#EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')  # mot de passe d'application
#EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER # Sender email must match the EMAIL_HOST_USER for Gmail

# ----------------------------------------------------------------------
# 3. SECURITY ADJUSTMENTS FOR TESTING
#
# This allows the external HTML file to make a POST request to your local Django server.
# For production, adjust these rules for proper security (e.g., using a specific domain).
# ----------------------------------------------------------------------
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1',
    'http://localhost',
    'https://hassen86naghmouchi.pythonanywhere.com',
    # If testing the HTML file separately, you might need its origin here
]
# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
# email end

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
EMAIL_PORT = 587
EMAIL_USE_TLS = True
#EMAIL_PORT = 465
#EMAIL_USE_TLS = False
#EMAIL_USE_SSL = True
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
